import { Activity, PresetIcon } from "./types";

export const ICON_TRANSLATIONS: Record<string, string> = {
  //icone estive
  "Ship": "Nave",
  "Waves": "Onde / Mare",
  "Sun": "Sole",
  "Sunset": "Tramonto",
  "Palmtree": "Palma",
  "IceCream": "Gelato",
  "Anchor": "Ancora",
  "Umbrella": "Ombrellone",
  "Tent": "Tenda / Campeggio",
  "Mountain": "Montagna",
  "Compass": "Bussola",
  "Backpack": "Zaino",
  "Binoculars": "Binocolo",
  "Bicycle": "Bicicletta",
  "Camera": "Fotocamera",
  "Ticket": "Biglietto",
  "Car": "Automobile",
  "Map": "Mappa",
  "Luggage": "Valigia",
  "Telescope": "Telescopio",
  "TreePine": "Pino",
  "Watermelon": "Anguria",
  "Sandal": "Sandalo",
  "Sunglasses": "Occhiali da sole",
  "Shell": "Conchiglia",
  "Sailboat": "Barca a vela",
  "LifeBuoy": "Salvagente",
  "Volleyball": "Beach volley",
  "CupSoda": "Bibita",
  "Beer": "Birra",
  "FlameKindling": "Falò",
  "MapPinned": "Posizione",
  "MountainSnow": "Ghiacciaio",
  "FishSymbol": "Pesca",
  "Wind": "Vento",
  "Grape": "Uva / Vino",
  "Pizza": "Pizza",
  "Flower2": "Fiore",
  "Bird": "Uccello",
  "Utensils": "Barbecue",
  "Dolphin": "Delfino",
  "CloudSun": "Sole e nuvole",
  "Banana": "Banana",
  "Cherry": "Ciliegia",
  "Sparkles": "Scintille",
  "Footprints": "Orme",
  "Salad": "Insalata",
  "Shrimp": "Gambero",
  "Citrus": "Limone",
  "Apple": "Mela",

  //balli
  "HighHeel": "Tacchi / Salsa",
  "Music": "Musica / Classica",
  "Disc": "Disco / Discoteca",
  "Drama": "Teatro",
  "PartyPopper": "Festa / Balli di gruppo",
  "AudioLines": "Zumba / Ritmo",
  "CassetteTape": "Hip hop",
  "Shuffle": "Shuffle",
  "Headphones": "Cuffie / Techno",
  "Mic": "Microfono / Musical",
  "Music2": "Caraibico",
  "Music3": "Valzer / Liscio",
  "Music4": "Tango / Bachata",
  "Flame": "Flamenco",
  "Speaker": "Cassa / Jazz",
  "HeartPulse": "Cardio dance",
  "Crown": "Corona",
  "Guitar": "Folk / Chitarra",
  "Activity": "Attività / Fitness",
  "Radio": "Street dance",

  //generali
  "Heart": "Cuore / Amore",
  "Coffee": "Caffè",
  "Dumbbell": "Palestra / Manubrio",
  "Smile": "Sorriso / Relax",
  "Clapperboard": "Ciak / Cinema",
  "Film": "Film / Tv",
  "BookOpen": "Libro aperto",
  "Briefcase": "Lavoro",
  "ShoppingBag": "Shopping",
  "Cake": "Torta",
  "Home": "Casa",
  "Landmark": "Banca",
  "Wine": "Vino",
  "Bed": "Letto / Sonno",
  "Dog": "Cane / Animali",
  "Stethoscope": "Salute / Medico",
  "ShoppingCart": "Spesa",
  "AlarmClock": "Sveglia",
  "Baby": "Bambino",
  "Bath": "Bagno / Igiene",
  "Bell": "Campana / Notifica",
  "Brain": "Mente / Studio",
  "Brush": "Pennello",
  "Bus": "Autobus",
  "Calculator": "Calcolatrice",
  "Calendar": "Calendario",
  "Candy": "Caramella",
  "ChefHat": "Cucina",
  "Cigarette": "Sigaretta",
  "Cloud": "Nuvola",
  "CloudRain": "Pioggia",
  "Code": "Codice / Programmazione",
  "Coins": "Monete",
  "Cookie": "Biscotto",
  "CreditCard": "Carta di credito",
  "Database": "Database",
  "Dices": "Dadi / Gioco",
  "DollarSign": "Guadagno",
  "Droplets": "Acqua",
  "Egg": "Uovo",
  "Eye": "Occhio",
  "Flag": "Traguardo",
  "Flashlight": "Torcia",
  "Frown": "Triste",
  "Fuel": "Benzina",
  "Gavel": "Legge",
  "Gift": "Regalo",
  "GlassWater": "Bicchiere",
  "Globe": "Internet",
  "GraduationCap": "Laurea",
  "Hammer": "Martello",
  "Hand": "Mano",
  "HelpingHand": "Aiuto",
  "Hourglass": "Clessidra",
  "Image": "Immagine",
  "Inbox": "E-mail",
  "Key": "Chiave",
  "Keyboard": "Tastiera",
  "Laptop": "Computer",
  "Leaf": "Foglia",
  "Library": "Biblioteca",
  "Lightbulb": "Lampadina",
  "Link": "Link",
  "ListTodo": "Lista cose da fare",
  "Mail": "Posta",
  "Megaphone": "Megafono",
  "MessageSquare": "Messaggio",
  "Microscope": "Microscopio",
  "Milk": "Latte",
  "Newspaper": "Giornale",
  "Package": "Pacco / Spedizione",
  "Palette": "Tavolozza",
  "Paperclip": "Graffetta",
  "PenTool": "Design",
  "PiggyBank": "Salvadanaio",
  "Printer": "Stampante",
  "Puzzle": "Puzzle",
  "QrCode": "Codice QR",
  "Receipt": "Scontrino",
  "Recycle": "Riciclo",
  "Refrigerator": "Frigorifero",
  "Rocket": "Razzo",
  "Ruler": "Righello",
  "Sandwich": "Panino",
  "Scale": "Bilancia",
  "Scissors": "Forbici",
  "Settings": "Impostazioni",
  "Shield": "Scudo / Sicurezza",
  "Shirt": "Abbigliamento",
  "ShowerHead": "Doccia",
  "Skull": "Teschio",
  "Smartphone": "Smartphone",
  "Soup": "Zuppa",
  "Sprout": "Germoglio",
  "Star": "Stella / Preferiti",
  "Tablet": "Tablet",
  "Target": "Obiettivo",
  "Terminal": "Terminale",
  "Thermometer": "Termometro",
  "ThumbsUp": "Mi piace",
  "ThumbsDown": "Non mi piace",
  "Timer": "Timer",
  "Trash2": "Cestino",
  "Truck": "Camion / Trasloco",
  "Tv": "Televisore",
  "User": "Incontro",
  "Users": "Gruppo / Social",
  "Wallet": "Portafoglio",
  "Watch": "Orologio",
  "Wrench": "Chiave inglese",
  "Zap": "Fulmine",
  "Cat": "Gatto",
  "Squirrel": "Scoiattolo",
  "BrickWall": "Ostacolo",
  "Clover": "Quadrifoglio / Fortuna",
  "Dna": "DNA",
  "DoorClosed": "Porta chiusa",
  "DoorOpen": "Porta aperta",
  "Drum": "Tamburo",
  "Eraser": "Gomma",
  "EyeOff": "Nascondi",
  "Factory": "Fabbrica",
  "Ghost": "Fantasma",
  "Hotel": "Hotel",
  "IdCard": "Documento",
  "Moon": "Luna",
  "Presentation": "Presentazione",
  "Soap": "Sapone",
  "AppWindow": "Finestra",
  "Archive": "Archivio",
  "Armchair": "Poltrona",
  "Bandage": "Cerotto",
  "BarChart": "Grafico",
  "Baseball": "Baseball",
  "Basketball": "Canestro",
  "Bitcoin": "Bitcoin",
  "Building": "Edificio",
  "Cable": "Cavo",
  "CigaretteOff": "Smettere fumo",
  "CloudLightning": "Fulmini",
  "CloudSnow": "Neve",
  "Cpu": "Processore",
  "Folder": "Cartella pc",
  "MoonStar": "Notte",
  "Network": "Rete pc",
  "Notebook": "Taccuino",
  "Nut": "Noci",
  "PhoneCall": "Telefonata",
  "Pipette": "Pipetta",
  "Play": "Avvia",
  "ShieldCheck": "Sicuro",
  "Unplug": "Disconnetti",
  "VolumeX": "Silenzioso",
  "Vote": "Voto",
  "ArrowUp": "Su",
  "ArrowDown": "Giù",
  "SearchCode": "Trova bug",
  "Gamepad": "Videogiochi",
  "CheckSquare": "Spuntato",
  "CheckCheck": "Letto",
  "CheckCircle": "Completato",

  // 50 Faccine con espressioni
  "FaceSmile": "Faccina Sorridente / Felice",
  "FaceFrown": "Faccina Triste / Malinconica",
  "FaceMeh": "Faccina Neutra / Indifferente",
  "FaceWink": "Faccina Occhiolino / Furbetta",
  "FaceLaugh": "Faccina con Risata / Contentissima",
  "FaceAngry": "Faccina Arrabbiata / Furiosa",
  "FaceWorried": "Faccina Preoccupata / Ansiosa",
  "FaceSurprised": "Faccina Sorpresa / Sbalordita",
  "FaceCry": "Faccina che Piange / Lacrime",
  "FaceLove": "Faccina Innamorata / Occhi a Cuore",
  "FaceCool": "Faccina Cool / Occhiali da Sole",
  "FaceSleep": "Faccina che Dorme / Sonnolenta",
  "FaceNervous": "Faccina Nervosa / Agitata",
  "FaceSweat": "Faccina Sudata / Sotto stress",
  "FaceKiss": "Faccina del Bacio / Affettuosa",
  "FaceTongue": "Faccina con Lingua di fuori / Scherzo",
  "FaceDizzy": "Faccina Confusa / Giramento di testa",
  "FaceBlush": "Faccina Imbarazzata / Guance rosse",
  "FaceShock": "Faccina Shockata / Spaventata",
  "FaceBored": "Faccina Annoiata / Scontenta",
  "FaceRelieved": "Faccina Sollevata / Rilassata",
  "FaceScream": "Faccina che Urla / Terrore",
  "FaceYawn": "Faccina che Sbadiglia / Stanca",
  "FaceSmug": "Faccina Presuntuosa / Furbastra",
  "FaceDetermined": "Faccina Determinata / Risoluta",
  "FaceSceptic": "Faccina Scettica / Dubbiosa",
  "FaceShy": "Faccina Timida / Riservata",
  "FaceSick": "Faccina Malata / Febbre",
  "FaceQuiet": "Faccina Silenziosa / Shh",
  "FaceThinking": "Faccina Pensierosa / Riflessiva",
  "FacePouting": "Faccina Offesa / Broncio",
  "FaceStarry": "Faccina Incoraggiata / Occhi Stellati",
  "FaceMonocle": "Faccina con Monocolo / Intellettuale",
  "FaceHalo": "Faccina con Aureola / Angelo",
  "FaceDevil": "Faccina Malvagia / Diavoletto",
  "FaceClown": "Faccina Clown / Pagliaccio",
  "FaceAlien": "Faccina Alieno / Extraterrestre",
  "FaceRobot": "Faccina Robot / Droide",
  "FaceCat": "Faccina Gatto / Felino",
  "FaceDog": "Faccina Cane / Cucciolo",
  "FaceRich": "Faccina con Dollari / Ricca",
  "FaceWhistling": "Faccina che Fischietta / Disinvolta",
  "FaceDisgusted": "Faccina Disgustata / Disapprovazione",
  "FaceSneezing": "Faccina con Starnuto / Raffreddata",
  "FaceDrooling": "Faccina con Bavetta / Desiderosa",
  "FaceHungry": "Faccina Affamata / Ghiotta",
  "FaceStudious": "Faccina Secchione / Studiosa",
  "FaceMuted": "Faccina con Bocca con Cerniera",
  "FaceExploding": "Faccina con Testa che Esplode / Straordinaria",
  "FaceHypnotized": "Faccina Ipnotizzata / Stupita",

  // 10 Faccine bimbi
  "KidCap": "Bimbo con Cappellino / Visiera",
  "KidBraids": "Bimba con Treccine / Capelli lunghi",
  "KidCurls": "Bimbo Riccio / Capelli ricci",
  "KidGlasses": "Bimbo con Occhiali / Simpatico",
  "KidCrown": "Bambino Principe / Corona regale",
  "KidRibbon": "Bimba con Fiocco / Capelli raccolti",
  "KidHeadphones": "Bimbo con Cuffie / Gamer",
  "KidBandana": "Bimbo con Bandana / Pirata",
  "KidHat": "Bimbo con Cappello di paglia / Sole",
  "KidBun": "Bimba con Codino / Chignon",

  // 20 Icone neonati e baby shower
  "BabyBottle": "Biberon",
  "BabyPacifier": "Ciuccio",
  "BabyStroller": "Passeggino",
  "BabyOnesie": "Body Neonato",
  "BabyRattle": "Sonaglio",
  "BabyCrib": "Culla",
  "BabySocks": "Calzine",
  "BabyDiaper": "Pannolino",
  "BabyBib": "Bavaglino",
  "BabyTeddy": "Orsetto Peluche",
  "BabyBalloon": "Palloncino Nascita",
  "BabyBlocks": "Cubi Giocattolo",
  "BabyDuck": "Paperella Bagnetto",
  "BabyElephant": "Elefantino",
  "BabyStork": "Cicogna Nascita",
  "BabySafetyPin": "Spilla da Balia",
  "BabyHeart": "Cuoricino",
  "BabyFootprint": "Piedino Neonato",
  "BabyMobile": "Giostrina Culla",
  "BabyCloud": "Nuvola Sogni",
  "BabyShower": "Festa Baby Shower",

  // 20 Icone Viaggio
  "TravelGlobe": "Mappamondo",
  "TravelPlane": "Aereo",
  "TravelSuitcase": "Valigia",
  "TravelMap": "Mappa",
  "TravelCompass": "Bussola",
  "TravelPassport": "Passaporto",
  "TravelCamera": "Macchina Fotografica",
  "TravelBackpack": "Zaino da Viaggio",
  "TravelHotel": "Hotel / Albergo",
  "TravelTent": "Tenda da Campeggio",
  "TravelBinoculars": "Binocolo",
  "TravelBeach": "Spiaggia e Palma",
  "TravelCampfire": "Fuoco da Campo",
  "TravelMountain": "Montagna",
  "TravelTickets": "Biglietti di Viaggio",
  "TravelCocktail": "Cocktail esotico",
  "TravelPostcard": "Cartolina di auguri",
  "TravelSunbed": "Lettino prendisole",
  "TravelLuggageTag": "Targhetta bagaglio",
  "TravelHotAirBalloon": "Mongolfiera",

  // 10 Icone Trasporti Urbani e Sharing
  "TransitScooter": "Monopattino Sharing",
  "TransitBike": "Bicicletta Sharing",
  "TransitCarRental": "Auto Sharing / Noleggio",
  "TransitBus": "Autobus Urbano",
  "TransitMetro": "Metropolitana",
  "TransitTrain": "Tram / Treno Cittadino",
  "TransitTaxi": "Taxi / Auto blu",
  "TransitWalk": "Percorso Pedonale",
  "TransitTicketSharing": "Abbonamento Trasporti",
  "TransitChargingStation": "Ricarica Elettrica",

  // 50 Icone Business e Affari (univochi per TypeScript compilation)
  "TrendingUp": "Crescita / Profitti",
  "TrendingDown": "Perdite / Spese Extra",
  "Euro": "Euro / Valuta",
  "UserCheck": "Nuovo Cliente",
  "Handshake": "Contratto / Accordo",
  "Building2": "Ufficio / Filiale",
  "FileCheck": "Pratica Approvata",
  "PieChart": "Bilancio / Quote",
  "BarChart3": "Vendite / Statistiche",
  "LineChart": "Performance Trend",
  "BriefcaseMedical": "Welfare Sanitario",
  "BadgePercent": "Percentuale Sconto",
  "MailOpen": "Email Marketing",
  "MessagesSquare": "Assistenza Supporto",
  "FolderKanban": "Bacheca Kanban",
  "Milestone": "Traguardo Roadmap",
  "CalendarCheck": "Fissato in Agenda",
  "HeartHandshake": "Customer Success",
  "PackageCheck": "Qualità Imballo",
  "Banknote": "Contanti / Banconote",
  "HandCoins": "Transazione Contante",
  "CircleDollarSign": "Moneta Dollaro",
  "CircleEuro": "Moneta Euro",
  "Gem": "Valore / Gemma",
  "Vault": "Cassaforte Valori",
  "Wallet2": "Portafoglio Alternativo",
  "BadgeDollarSign": "Premio Dollaro",
  "BadgeEuro": "Premio Euro",
  "BadgeSwissFranc": "Premio Franco Svizzero",
  "BadgePound": "Premio Sterlina",
  "ReceiptCent": "Ricevuta Centesimi",
  "ReceiptDollarSign": "Ricevuta Dollaro",
  "ReceiptEuro": "Ricevuta Euro",
  "SquareDollarSign": "Valuta Dollaro",
  "SquareEuro": "Valuta Euro",
  "Store": "Negozio / Shop",
  "Tag": "Prezzo / Offerta",
  "Tags": "Etichette Prezzi"
};

export const PASTEL_COLORS = [
  { id: "rose", name: "Rosa", bg: "bg-rose-50", text: "text-rose-600", border: "border-rose-200", focusBg: "focus:ring-rose-300", accent: "rose" },
  { id: "amber", name: "Arancio", bg: "bg-amber-50", text: "text-amber-600", border: "border-amber-200", focusBg: "focus:ring-amber-300", accent: "amber" },
  { id: "emerald", name: "Verde", bg: "bg-emerald-50", text: "text-emerald-600", border: "border-emerald-200", focusBg: "focus:ring-emerald-300", accent: "emerald" },
  { id: "sky", name: "Azzurro", bg: "bg-sky-50", text: "text-sky-600", border: "border-sky-200", focusBg: "focus:ring-sky-300", accent: "sky" },
  { id: "indigo", name: "Indaco", bg: "bg-indigo-50", text: "text-indigo-600", border: "border-indigo-200", focusBg: "focus:ring-indigo-300", accent: "indigo" },
  { id: "violet", name: "Viola", bg: "bg-violet-50", text: "text-violet-600", border: "border-violet-200", focusBg: "focus:ring-violet-300", accent: "violet" },
  { id: "fuchsia", name: "Fucsia", bg: "bg-fuchsia-50", text: "text-fuchsia-600", border: "border-fuchsia-200", focusBg: "focus:ring-fuchsia-300", accent: "fuchsia" },
  { id: "slate", name: "Grigio", bg: "bg-slate-50", text: "text-slate-600", border: "border-slate-200", focusBg: "focus:ring-slate-300", accent: "slate" },
];

export const PRESET_ICONS: PresetIcon[] = [
  // ==========================================
  // --- 50 ICONE ESTIVE (UNIVOCHE, SENZA DOPPIONI) ---
  // ==========================================
  { name: "Ship", label: "Crociera di lusso", category: "summer" },
  { name: "Waves", label: "Nuotare nel mare / Onde", category: "summer" },
  { name: "Sun", label: "Prendere il sole / Spiaggia", category: "summer" },
  { name: "Sunset", label: "Aperitivo al tramonto", category: "summer" },
  { name: "Palmtree", label: "Ombra sotto le palme", category: "summer" },
  { name: "IceCream", label: "Coppa Gelato / Gelateria", category: "summer" },
  { name: "Anchor", label: "Gita in gommone / Barca", category: "summer" },
  { name: "Umbrella", label: "Relax sotto l'ombrellone", category: "summer" },
  { name: "Tent", label: "Dormire in tenda / Campeggio", category: "summer" },
  { name: "Mountain", label: "Trekking nei sentieri", category: "summer" },
  { name: "Compass", label: "Avventura estiva", category: "summer" },
  { name: "Backpack", label: "Escursione con lo zaino", category: "summer" },
  { name: "Binoculars", label: "Avvistamento natura / Birdwatching", category: "summer" },
  { name: "Bicycle", label: "Pedalata estiva al tramonto", category: "summer" },
  { name: "Camera", label: "Scattare foto ricordo", category: "summer" },
  { name: "Ticket", label: "Cinema all'aperto / Festival", category: "summer" },
  { name: "Car", label: "Gita fuori porta / On the Road", category: "summer" },
  { name: "Map", label: "Pianificazione viaggi", category: "summer" },
  { name: "Luggage", label: "Fare le valigie", category: "summer" },
  { name: "Telescope", label: "Guardare le stelle cadenti", category: "summer" },
  { name: "TreePine", label: "Escursione in pineta fresca", category: "summer" },
  { name: "Watermelon", label: "Fetta d'anguria gelata", category: "summer" },
  { name: "Sandal", label: "Ciabatte infradito / Mare", category: "summer" },
  { name: "Sunglasses", label: "Occhiali da sole alla moda", category: "summer" },
  { name: "Shell", label: "Raccolta conchiglie in spiaggia", category: "summer" },
  { name: "Sailboat", label: "Gita in barca a vela", category: "summer" },
  { name: "LifeBuoy", label: "Bagno con salvagente", category: "summer" },
  { name: "Volleyball", label: "Beach volley sulla sabbia", category: "summer" },
  { name: "CupSoda", label: "Drink fresco / Chiringuito", category: "summer" },
  { name: "Beer", label: "Birra gelata al chiosco", category: "summer" },
  { name: "FlameKindling", label: "Chitarra e falò sulla spiaggia", category: "summer" },
  { name: "MapPinned", label: "Trovare la strada del resort", category: "summer" },
  { name: "MountainSnow", label: "Alpinismo estivo su ghiacciai", category: "summer" },
  { name: "FishSymbol", label: "Battuta di pesca all'alba", category: "summer" },
  { name: "Wind", label: "Brezza marina rinfrescante", category: "summer" },
  { name: "Grape", label: "Degustazione vini estivi / Cantina", category: "summer" },
  { name: "Pizza", label: "Cena all'aperto / Pizza party", category: "summer" },
  { name: "Flower2", label: "Cogliere fiori di campo", category: "summer" },
  { name: "Bird", label: "Ascoltare cinguettio d'estate", category: "summer" },
  { name: "Utensils", label: "Barbecue estivo / Grigliata", category: "summer" },
  { name: "Dolphin", label: "Avvistamento delfini in barca", category: "summer" },
  { name: "CloudSun", label: "Giorno soleggiato con nuvole", category: "summer" },
  { name: "Banana", label: "Spuntino di frutta dissetante", category: "summer" },
  { name: "Cherry", label: "Mangiare ciliegie fresche", category: "summer" },
  { name: "Sparkles", label: "Notte magica sotto le stelle", category: "summer" },
  { name: "Footprints", label: "Passeggiata sulla sabbia", category: "summer" },
  { name: "Salad", label: "Pranzo leggero / Insalata estiva", category: "summer" },
  { name: "Shrimp", label: "Cena di pesce fresco o frittura", category: "summer" },
  { name: "Citrus", label: "Limonata fresca o spremuta", category: "summer" },
  { name: "Apple", label: "Picnic estivo nel parco", category: "summer" },

  // ==========================================
  // --- 20 ICONE DI BALLI (UNIVOCHE, SENZA DOPPIONI) ---
  // ==========================================
  { name: "HighHeel", label: "Salsa / Bachata / Tacchi", category: "dance" },
  { name: "Music", label: "Danza classica / Balletto", category: "dance" },
  { name: "Disc", label: "Disco Music / Serata in Discoteca", category: "dance" },
  { name: "Drama", label: "Danza teatrale e contemporanea", category: "dance" },
  { name: "PartyPopper", label: "Balli di gruppo / Festa", category: "dance" },
  { name: "AudioLines", label: "Zumba fitness / Ballo a ritmo", category: "dance" },
  { name: "CassetteTape", label: "Funk, Hip-hop o Breakdance", category: "dance" },
  { name: "Shuffle", label: "Shuffle Dance / Electro", category: "dance" },
  { name: "Headphones", label: "Electro Dance e Techno", category: "dance" },
  { name: "Mic", label: "Musical / Canto e Ballo", category: "dance" },
  { name: "Music2", label: "Danze Caraibiche", category: "dance" },
  { name: "Music3", label: "Valzer e Ballo liscio", category: "dance" },
  { name: "Music4", label: "Kizomba, Bachata Sensual o Tango", category: "dance" },
  { name: "Flame", label: "Flamenco passionale", category: "dance" },
  { name: "Speaker", label: "Danza Jazz o Moderna", category: "dance" },
  { name: "HeartPulse", label: "Cardio Dance / Zumba energetica", category: "dance" },
  { name: "Crown", label: "Ballo da sala regale / Grand Valzer", category: "dance" },
  { name: "Guitar", label: "Tarantella / Ballo folk", category: "dance" },
  { name: "Activity", label: "Ballo fitness / Coreografia attiva", category: "dance" },
  { name: "Radio", label: "Danza di strada / Street dance", category: "dance" },

  // ==========================================
  // --- ICONE GENERALI DELLA VITA QUOTIDIANA ---
  // ==========================================
  { name: "Heart", label: "Amore / Relazione", category: "general" },
  { name: "Coffee", label: "Caffè / Break", category: "general" },
  { name: "Dumbbell", label: "Esercizi in palestra / Pesi", category: "general" },
  { name: "Smile", label: "Divertimento / Relax / Felicità", category: "general" },
  { name: "Clapperboard", label: "Cinema / Spettacolo", category: "general" },
  { name: "Film", label: "Film / Serie TV in streaming", category: "general" },
  { name: "BookOpen", label: "Lettura / Studio / Libri", category: "general" },
  { name: "Briefcase", label: "Lavoro / Ufficio / Professione", category: "general" },
  { name: "ShoppingBag", label: "Shopping / Negozi", category: "general" },
  { name: "Cake", label: "Compleanno / Anniversario / Dolce", category: "general" },
  { name: "Home", label: "Spese di casa / Affitto", category: "general" },
  { name: "Landmark", label: "Mutuo / Banca / Finanze", category: "general" },
  { name: "Wine", label: "Aperitivo / Cocktail", category: "general" },
  { name: "Bed", label: "Dormire / Riposo / Sonno", category: "general" },
  { name: "Dog", label: "Animali domestici / Cani", category: "general" },
  { name: "Stethoscope", label: "Visita medica / Salute", category: "general" },
  { name: "ShoppingCart", label: "Spesa al supermercato", category: "general" },
  { name: "AlarmClock", label: "Sveglia mattutina / Scadenza", category: "general" },
  { name: "Baby", label: "Bambini / Bebè", category: "general" },
  { name: "Bath", label: "Doccia / Vasca / Igiene", category: "general" },
  { name: "Bell", label: "Notifica / Promemoria", category: "general" },
  { name: "Brain", label: "Studio intenso / Ragionamento / Concentrazione", category: "general" },
  { name: "Brush", label: "Pennello / Pittura / Arte", category: "general" },
  { name: "Bus", label: "Mezzi pubblici / Autobus / Viaggi", category: "general" },
  { name: "Calculator", label: "Calcolo spese / Matematica", category: "general" },
  { name: "Calendar", label: "Agenda / Calendario degli impegni", category: "general" },
  { name: "Candy", label: "Caramelle / Dolcetti", category: "general" },
  { name: "ChefHat", label: "Cucinare / Preparare piatti", category: "general" },
  { name: "Cigarette", label: "Pausa sigaretta", category: "general" },
  { name: "Cloud", label: "Tempo nuvoloso", category: "general" },
  { name: "CloudRain", label: "Brutto tempo / Pioggia", category: "general" },
  { name: "Code", label: "Programmazione / Web Development", category: "general" },
  { name: "Coins", label: "Spiccioli / Risparmi monetari", category: "general" },
  { name: "Cookie", label: "Biscotto / Spuntino dolce", category: "general" },
  { name: "CreditCard", label: "Pagamento elettronico", category: "general" },
  { name: "Database", label: "Gestione database / Server IT", category: "general" },
  { name: "Dices", label: "Giochi da tavolo / Dadi", category: "general" },
  { name: "DollarSign", label: "Entrate monetarie / Guadagno", category: "general" },
  { name: "Droplets", label: "Acqua / Sete / Bere", category: "general" },
  { name: "Egg", label: "Colazione con uova / Cibo bio", category: "general" },
  { name: "Eye", label: "Visita oculistica / Controllo", category: "general" },
  { name: "Flag", label: "Obiettivo raggiunto / Traguardo / Sfida", category: "general" },
  { name: "Flashlight", label: "Luce / Ispezione / Torcia", category: "general" },
  { name: "Frown", label: "Momento triste / Delusione", category: "general" },
  { name: "Fuel", label: "Benzina / Carburante per l'auto", category: "general" },
  { name: "Gavel", label: "Pratiche legali / Tribunale", category: "general" },
  { name: "Gift", label: "Regalo di Natale / Sorpresa", category: "general" },
  { name: "GlassWater", label: "Idratazione / Acqua", category: "general" },
  { name: "Globe", label: "Sito web / Internet", category: "general" },
  { name: "GraduationCap", label: "Laurea / Diploma", category: "general" },
  { name: "Hammer", label: "Fai da te / Lavoretti in casa", category: "general" },
  { name: "Hand", label: "Mano / Stop / Saluto", category: "general" },
  { name: "HelpingHand", label: "Fare volontariato / Aiutare qualcuno", category: "general" },
  { name: "Hourglass", label: "Tempo d'attesa lungo", category: "general" },
  { name: "Image", label: "Galleria foto / Quadri", category: "general" },
  { name: "Inbox", label: "Leggere email ricevute", category: "general" },
  { name: "Key", label: "Chiavi di casa", category: "general" },
  { name: "Keyboard", label: "Scrivere al computer", category: "general" },
  { name: "Laptop", label: "Lavoro al PC portatile", category: "general" },
  { name: "Leaf", label: "Foglia / Natura / Ecologia", category: "general" },
  { name: "Library", label: "Andare in biblioteca", category: "general" },
  { name: "Lightbulb", label: "Nuova idea brillante / Ispirazione", category: "general" },
  { name: "Link", label: "Collegamenti utili / Social network", category: "general" },
  { name: "ListTodo", label: "Lista cosa da fare / Task list", category: "general" },
  { name: "Mail", label: "Lettere cartacee", category: "general" },
  { name: "Megaphone", label: "Annuncio importante / Chiamata di gruppo", category: "general" },
  { name: "MessageSquare", label: "Messaggiare / Chiacchierare", category: "general" },
  { name: "Microscope", label: "Ricerca scientifica / Esami di laboratorio", category: "general" },
  { name: "Milk", label: "Colazione con latte", category: "general" },
  { name: "Newspaper", label: "Leggere giornale", category: "general" },
  { name: "Package", label: "Ricevuto pacco / Spedizione", category: "general" },
  { name: "Palette", label: "Pittura / Creazione artistica", category: "general" },
  { name: "Paperclip", label: "Documenti d'ufficio", category: "general" },
  { name: "PenTool", label: "Grafica digitale / Design", category: "general" },
  { name: "PiggyBank", label: "Mettere soldi da parte", category: "general" },
  { name: "Printer", label: "Stampare documenti", category: "general" },
  { name: "Puzzle", label: "Risolvere un puzzle / Rompicapo", category: "general" },
  { name: "QrCode", label: "Scansionare QR code", category: "general" },
  { name: "Receipt", label: "Contabilità scontrini", category: "general" },
  { name: "Recycle", label: "Raccolta differenziata", category: "general" },
  { name: "Refrigerator", label: "Sistemare la spesa nel frigo", category: "general" },
  { name: "Rocket", label: "Avvio nuovo progetto importante", category: "general" },
  { name: "Ruler", label: "Misurare spazi / Arredamento", category: "general" },
  { name: "Sandwich", label: "Mangiare un panino", category: "general" },
  { name: "Scale", label: "Controllo peso / Bilancia nutrizionale", category: "general" },
  { name: "Scissors", label: "Taglio capelli / Forbici", category: "general" },
  { name: "Settings", label: "Configurazioni sistema / Opzioni", category: "general" },
  { name: "Shield", label: "Scudo protettivo", category: "general" },
  { name: "Shirt", label: "Stirare vestiti / Shopping abbigliamento", category: "general" },
  { name: "ShowerHead", label: "Farsi la doccia", category: "general" },
  { name: "Skull", label: "Film horror / Cimitero", category: "general" },
  { name: "Smartphone", label: "Navigare su smartphone", category: "general" },
  { name: "Soup", label: "Cena con zuppa calda", category: "general" },
  { name: "Sprout", label: "Natura / Coltivare piante", category: "general" },
  { name: "Star", label: "Preferito / Successo incredibile", category: "general" },
  { name: "Tablet", label: "Leggere su tablet", category: "general" },
  { name: "Target", label: "Messa a fuoco obiettivi", category: "general" },
  { name: "Terminal", label: "Sviluppatore software / Shell computer", category: "general" },
  { name: "Thermometer", label: "Febbre / Misurare la temperatura corporea", category: "general" },
  { name: "ThumbsUp", label: "Soddisfazione / Approvare", category: "general" },
  { name: "ThumbsDown", label: "Momento no / Disapprovare", category: "general" },
  { name: "Timer", label: "Timer cucina / Studio pomodoro", category: "general" },
  { name: "Trash2", label: "Pulizie di casa / Buttare spazzatura", category: "general" },
  { name: "Truck", label: "Trasloco casa", category: "general" },
  { name: "Tv", label: "Guardare la televisione", category: "general" },
  { name: "User", label: "Incontro a due", category: "general" },
  { name: "Users", label: "Riunione di gruppo", category: "general" },
  { name: "Wallet", label: "Portafoglio pieno / Spese", category: "general" },
  { name: "Watch", label: "Controllare il tempo", category: "general" },
  { name: "Wrench", label: "Riparazioni idrauliche", category: "general" },
  { name: "Zap", label: "Idea folgorante / Flash energetico", category: "general" },
  { name: "Cat", label: "Gatto di casa", category: "general" },
  { name: "Squirrel", label: "Bosco / Scoiattolo", category: "general" },
  { name: "BrickWall", label: "Momento di blocco", category: "general" },
  { name: "Clover", label: "Fortuna sfacciata", category: "general" },
  { name: "Dna", label: "Analisi biologiche", category: "general" },
  { name: "DoorClosed", label: "Rimanere in casa", category: "general" },
  { name: "DoorOpen", label: "Uscire di casa", category: "general" },
  { name: "Drum", label: "Lezione di musica / Batteria", category: "general" },
  { name: "Eraser", label: "Dimenticare errore", category: "general" },
  { name: "EyeOff", label: "Momento privato", category: "general" },
  { name: "Factory", label: "Lavoro in stabilimento", category: "general" },
  { name: "Ghost", label: "Serata misteriosa", category: "general" },
  { name: "Hotel", label: "Soggiorno in albergo", category: "general" },
  { name: "IdCard", label: "Rinnovare documenti", category: "general" },
  { name: "Moon", label: "Dormire di notte", category: "general" },
  { name: "Presentation", label: "Esposizione e slide", category: "general" },
  { name: "Soap", label: "Igiene personale / Sapone", category: "general" },
  { name: "AppWindow", label: "Configurazione software", category: "general" },
  { name: "Archive", label: "Archiviazione faldoni", category: "general" },
  { name: "Armchair", label: "Poltrona comodissima", category: "general" },
  { name: "Bandage", label: "Medicazione ferita / Cerotto", category: "general" },
  { name: "BarChart", label: "Studio performance mensili", category: "general" },
  { name: "Baseball", label: "Partita a baseball", category: "general" },
  { name: "Basketball", label: "Partita a pallacanestro", category: "general" },
  { name: "Bitcoin", label: "Andamento crypto", category: "general" },
  { name: "Building", label: "Andare in centro città", category: "general" },
  { name: "Cable", label: "Sistemare cavi aggrovigliati", category: "general" },
  { name: "CigaretteOff", label: "Smettere di fumare", category: "general" },
  { name: "CloudLightning", label: "Temporale estivo improvviso", category: "general" },
  { name: "CloudSnow", label: "Giornata sulla neve", category: "general" },
  { name: "Cpu", label: "Sostituzione scheda PC", category: "general" },
  { name: "Folder", label: "Organizzare cartelle pc", category: "general" },
  { name: "MoonStar", label: "Notte stellata", category: "general" },
  { name: "Network", label: "Progetto aziendale multiuso", category: "general" },
  { name: "Notebook", label: "Prendere appunti a mano", category: "general" },
  { name: "Nut", label: "Mangiare frutta secca salutare", category: "general" },
  { name: "PhoneCall", label: "Telefonata importante", category: "general" },
  { name: "Pipette", label: "Cura della pelle con siero", category: "general" },
  { name: "Play", label: "Ascolto canzone", category: "general" },
  { name: "ShieldCheck", label: "Antivirus o account protetto", category: "general" },
  { name: "Unplug", label: "Momento di offline totale", category: "general" },
  { name: "VolumeX", label: "Silenziare disturbi", category: "general" },
  { name: "Vote", label: "Andare a votare / Elezioni", category: "general" },
  { name: "ArrowUp", label: "Miglioramento dell'umore", category: "general" },
  { name: "ArrowDown", label: "Oscillazione al ribasso", category: "general" },
  { name: "SearchCode", label: "Rilevamento bachi codice", category: "general" },
  { name: "Gamepad", label: "Competizione videogiochi", category: "general" },
  { name: "CheckSquare", label: "Verifica certificazione", category: "general" },
  { name: "CheckCheck", label: "Doppia spunta / Letto", category: "general" },
  { name: "CheckCircle", label: "Target validato", category: "general" },

  // ==========================================
  // --- 50 ICONE FACCINE CON ESPRESSIONI VARIE ---
  // ==========================================
  { name: "FaceSmile", label: "Faccina Sorridente / Allegra", category: "faces" },
  { name: "FaceFrown", label: "Faccina Triste / Scontenta", category: "faces" },
  { name: "FaceMeh", label: "Faccina Neutra / Indifferente", category: "faces" },
  { name: "FaceWink", label: "Faccina Occhiolino / Furbetta", category: "faces" },
  { name: "FaceLaugh", label: "Faccina Sorridente con Risata", category: "faces" },
  { name: "FaceAngry", label: "Faccina Arrabbiata / Furiosa", category: "faces" },
  { name: "FaceWorried", label: "Faccina Preoccupata / Ansiosa", category: "faces" },
  { name: "FaceSurprised", label: "Faccina Sorpresa / Sbalordita", category: "faces" },
  { name: "FaceCry", label: "Faccina che Piange con Lacrime", category: "faces" },
  { name: "FaceLove", label: "Faccina Innamorata con Occhi a Cuore", category: "faces" },
  { name: "FaceCool", label: "Faccina Cool con Occhiali da Sole", category: "faces" },
  { name: "FaceSleep", label: "Faccina che Dorme / Sognatrice", category: "faces" },
  { name: "FaceNervous", label: "Faccina Nervosa / Agitata", category: "faces" },
  { name: "FaceSweat", label: "Faccina con Sudorazione / Preoccupata", category: "faces" },
  { name: "FaceKiss", label: "Faccina del Bacio / Affettuosa", category: "faces" },
  { name: "FaceTongue", label: "Faccina con Lingua di Fuori / Giocherellona", category: "faces" },
  { name: "FaceDizzy", label: "Faccina Stordita / Confusa", category: "faces" },
  { name: "FaceBlush", label: "Faccina Imbarazzata / Arrossita", category: "faces" },
  { name: "FaceShock", label: "Faccina Spaventata / Scioccata", category: "faces" },
  { name: "FaceBored", label: "Faccina Annoiata / Scontenta", category: "faces" },
  { name: "FaceRelieved", label: "Faccina Sollevata / Calma", category: "faces" },
  { name: "FaceScream", label: "Faccina che Urla terrorizzata", category: "faces" },
  { name: "FaceYawn", label: "Faccina che Sbadiglia per stanchezza", category: "faces" },
  { name: "FaceSmug", label: "Faccina Compiaciuta / Orgogliosa", category: "faces" },
  { name: "FaceDetermined", label: "Faccina Determinata / Grintosa", category: "faces" },
  { name: "FaceSceptic", label: "Faccina Scettica / Sospettosa", category: "faces" },
  { name: "FaceShy", label: "Faccina Timida / Riservata", category: "faces" },
  { name: "FaceSick", label: "Faccina Malata con Termometro", category: "faces" },
  { name: "FaceQuiet", label: "Faccina Silenziosa con mano davanti", category: "faces" },
  { name: "FaceThinking", label: "Faccina Pensierosa / Dubbiosa", category: "faces" },
  { name: "FacePouting", label: "Faccina Offesa / Broncio", category: "faces" },
  { name: "FaceStarry", label: "Faccina con Occhi Stellati", category: "faces" },
  { name: "FaceMonocle", label: "Faccina con Monocolo elegante", category: "faces" },
  { name: "FaceHalo", label: "Faccina con Aureola / Angioletto", category: "faces" },
  { name: "FaceDevil", label: "Faccina Diavoletto Sorridente", category: "faces" },
  { name: "FaceClown", label: "Faccina Clown / Truccata", category: "faces" },
  { name: "FaceAlien", label: "Faccina Alieno dello Spazio", category: "faces" },
  { name: "FaceRobot", label: "Faccina Robot / Meccanica", category: "faces" },
  { name: "FaceCat", label: "Faccina Gatto / Miao", category: "faces" },
  { name: "FaceDog", label: "Faccina Cane / Bau", category: "faces" },
  { name: "FaceRich", label: "Faccina con Dollari / Ricchezza", category: "faces" },
  { name: "FaceWhistling", label: "Faccina che Fischietta allegra", category: "faces" },
  { name: "FaceDisgusted", label: "Faccina Disgustata / Smorfia", category: "faces" },
  { name: "FaceSneezing", label: "Faccina che Starnutisce con fazzoletto", category: "faces" },
  { name: "FaceDrooling", label: "Faccina che sbava per acquolina", category: "faces" },
  { name: "FaceHungry", label: "Faccina Affamata che si lecca i baffi", category: "faces" },
  { name: "FaceStudious", label: "Faccina Secchione con Occhiali da vista", category: "faces" },
  { name: "FaceMuted", label: "Faccina con Bocca Cerniera", category: "faces" },
  { name: "FaceExploding", label: "Faccina con Testa Fredda che Esplode", category: "faces" },
  { name: "FaceHypnotized", label: "Faccina Ipnotizzata / Gira occhi", category: "faces" },

  // ==========================================
  // --- 10 ICONE FACCINE BIMBI ---
  // ==========================================
  { name: "KidCap", label: "Bambino con Cappellino sportivo", category: "kids" },
  { name: "KidBraids", label: "Bambina con graziose Treccine", category: "kids" },
  { name: "KidCurls", label: "Bambino con Capelli Ricci", category: "kids" },
  { name: "KidGlasses", label: "Bambino simpatico con Occhiali", category: "kids" },
  { name: "KidCrown", label: "Bambino Principe con Corona", category: "kids" },
  { name: "KidRibbon", label: "Bambina con Fiocco nei capelli", category: "kids" },
  { name: "KidHeadphones", label: "Bambino Moderno con Cuffie", category: "kids" },
  { name: "KidBandana", label: "Bambino Pirata con Bandana", category: "kids" },
  { name: "KidHat", label: "Bambino con Cappello di Paglia", category: "kids" },
  { name: "KidBun", label: "Bambina con Chignon o codino", category: "kids" },

  // ==========================================
  // --- 20 ICONE NEONATI E BABY SHOWER ---
  // ==========================================
  { name: "BabyBottle", label: "Biberon latte calco", category: "babies" },
  { name: "BabyPacifier", label: "Ciuccio calmante", category: "babies" },
  { name: "BabyStroller", label: "Passeggino o carrozzina", category: "babies" },
  { name: "BabyOnesie", label: "Body per bebè", category: "babies" },
  { name: "BabyRattle", label: "Sonaglio colorato", category: "babies" },
  { name: "BabyCrib", label: "Culla nanna dolci sogni", category: "babies" },
  { name: "BabySocks", label: "Calzine per neonato", category: "babies" },
  { name: "BabyDiaper", label: "Pannolino cambio bebè", category: "babies" },
  { name: "BabyBib", label: "Bavaglino pappa", category: "babies" },
  { name: "BabyTeddy", label: "Orsetto peluche", category: "babies" },
  { name: "BabyBalloon", label: "Palloncino elio festa", category: "babies" },
  { name: "BabyBlocks", label: "Cubi lettere giocattolo", category: "babies" },
  { name: "BabyDuck", label: "Paperella di gomma bagno", category: "babies" },
  { name: "BabyElephant", label: "Elefantino nursery", category: "babies" },
  { name: "BabyStork", label: "Cicogna che porta il bebè", category: "babies" },
  { name: "BabySafetyPin", label: "Spilla da balia classica", category: "babies" },
  { name: "BabyHeart", label: "Cuoricino dolcezza", category: "babies" },
  { name: "BabyFootprint", label: "Piedino o impronta neonato", category: "babies" },
  { name: "BabyMobile", label: "Giostrina stelline carosello", category: "babies" },
  { name: "BabyCloud", label: "Nuvola sogni o pioggia d'amore", category: "babies" },
  { name: "BabyShower", label: "Festa Baby Shower regali eventi", category: "babies" },

  // ==========================================
  // --- 20 ICONE VIAGGIO ---
  // ==========================================
  { name: "TravelGlobe", label: "Mappamondo avventura", category: "travel" },
  { name: "TravelPlane", label: "Aereo volo decollo", category: "travel" },
  { name: "TravelSuitcase", label: "Valigia bagaglio trolley", category: "travel" },
  { name: "TravelMap", label: "Mappa stradale itinerario", category: "travel" },
  { name: "TravelCompass", label: "Bussola orientamento nord", category: "travel" },
  { name: "TravelPassport", label: "Passaporto visti viaggi", category: "travel" },
  { name: "TravelCamera", label: "Fotocamera scatta ricordi", category: "travel" },
  { name: "TravelBackpack", label: "Zaino scout escursioni", category: "travel" },
  { name: "TravelHotel", label: "Hotel pernottamento stelle", category: "travel" },
  { name: "TravelTent", label: "Tenda campeggio natura", category: "travel" },
  { name: "TravelBinoculars", label: "Binocolo avvistamento fauna", category: "travel" },
  { name: "TravelBeach", label: "Spiaggia esotica e palma", category: "travel" },
  { name: "TravelCampfire", label: "Fuoco da bivacco marshmallow", category: "travel" },
  { name: "TravelMountain", label: "Montagna scalata vette", category: "travel" },
  { name: "TravelTickets", label: "Biglietti aereo treno", category: "travel" },
  { name: "TravelCocktail", label: "Cocktail drink estivo", category: "travel" },
  { name: "TravelPostcard", label: "Cartolina postale saluti", category: "travel" },
  { name: "TravelSunbed", label: "Lettino relax spiaggia", category: "travel" },
  { name: "TravelLuggageTag", label: "Targhetta bagaglio bag", category: "travel" },
  { name: "TravelHotAirBalloon", label: "Mongolfiera volo libero", category: "travel" },

  // ==========================================
  // --- 10 ICONE TRASPORTI URBANI E SHARING ---
  // ==========================================
  { name: "TransitScooter", label: "Monopattino elettrico sharing", category: "transit" },
  { name: "TransitBike", label: "Bicicletta pedalata sharing", category: "transit" },
  { name: "TransitCarRental", label: "Auto a noleggio car sharing", category: "transit" },
  { name: "TransitBus", label: "Autobus comunale pullman", category: "transit" },
  { name: "TransitMetro", label: "Metropolitana sotterranea metro", category: "transit" },
  { name: "TransitTrain", label: "Tram urbano o treno", category: "transit" },
  { name: "TransitTaxi", label: "Taxi servizio corsa", category: "transit" },
  { name: "TransitWalk", label: "Tratta a piedi camminata", category: "transit" },
  { name: "TransitTicketSharing", label: "Biglietto elettronico o abbonamento", category: "transit" },
  { name: "TransitChargingStation", label: "Punto ricarica elettrica veicoli", category: "transit" },

  // ==========================================
  // --- 50 ICONE BUSINESS E AFFARI ---
  // ==========================================
  { name: "Briefcase", label: "Valigetta lavoro e compiti", category: "business" },
  { name: "TrendingUp", label: "Crescita vendite o trend positivo", category: "business" },
  { name: "TrendingDown", label: "Perdite o spese impreviste", category: "business" },
  { name: "DollarSign", label: "Entrate in dollari o guadagno", category: "business" },
  { name: "Euro", label: "Fatturato in euro o pagamenti", category: "business" },
  { name: "CreditCard", label: "Spese con carta di credito", category: "business" },
  { name: "Users", label: "Meeting di team o clienti", category: "business" },
  { name: "UserCheck", label: "Nuovo cliente o lead approvato", category: "business" },
  { name: "Handshake", label: "Accordo concluso o stretta di mano", category: "business" },
  { name: "Building", label: "Sede centrale o edificio aziendale", category: "business" },
  { name: "Building2", label: "Ufficio, filiale o agenzia", category: "business" },
  { name: "FileText", label: "Contratto o documento da firmare", category: "business" },
  { name: "FileCheck", label: "Pratica o fattura approvata", category: "business" },
  { name: "Receipt", label: "Scontrino fiscale o rimborso spese", category: "business" },
  { name: "PieChart", label: "Ripartizione bilancio o quote", category: "business" },
  { name: "BarChart3", label: "Statistiche vendite o diagramma", category: "business" },
  { name: "LineChart", label: "Performance mensili o grafico", category: "business" },
  { name: "Presentation", label: "Pitch di vendita o presentazione", category: "business" },
  { name: "Calculator", label: "Contabilità, calcoli o tasse", category: "business" },
  { name: "Percent", label: "Provvigioni o sconti commerciali", category: "business" },
  { name: "PiggyBank", label: "Salvadanaio o risparmio aziendale", category: "business" },
  { name: "Target", label: "Obiettivo commerciale o KPI", category: "business" },
  { name: "Award", label: "Premio di produzione o certificazione", category: "business" },
  { name: "Wallet", label: "Portafoglio o fondo cassa", category: "business" },
  { name: "Scale", label: "Ufficio legale o compliance", category: "business" },
  { name: "BriefcaseMedical", label: "Piano sanitario o welfare dipendenti", category: "business" },
  { name: "Globe", label: "Clienti esteri o internazionalizzazione", category: "business" },
  { name: "BadgePercent", label: "Sconto speciale o promozione", category: "business" },
  { name: "Coins", label: "Liquidità o gettoni presenza", category: "business" },
  { name: "Megaphone", label: "Campagna pubblicitaria o annuncio", category: "business" },
  { name: "Network", label: "Incontro di networking o partnership", category: "business" },
  { name: "PenTool", label: "Firma digitale o stesura accordo", category: "business" },
  { name: "Smartphone", label: "Telefonata di lavoro o assistente", category: "business" },
  { name: "MailOpen", label: "E-mail marketing o newsletter ricevuta", category: "business" },
  { name: "MessagesSquare", label: "Supporto clienti o assistenza", category: "business" },
  { name: "FolderKanban", label: "Gestione bacheca progetti o task", category: "business" },
  { name: "Milestone", label: "Milestone o punto di svolta progetto", category: "business" },
  { name: "Notebook", label: "Note e appunti delle riunioni", category: "business" },
  { name: "CalendarCheck", label: "Incontro fissato in agenda", category: "business" },
  { name: "SearchCode", label: "Ricerca di mercato o bug-hunting", category: "business" },
  { name: "Clock", label: "Time tracking o ore fatturabili", category: "business" },
  { name: "ShieldCheck", label: "Trattamento dati, GDPR o sicurezza", category: "business" },
  { name: "HeartHandshake", label: "Customer success o fidelizzazione", category: "business" },
  { name: "Flame", label: "Idea startup ad alto potenziale", category: "business" },
  { name: "Rocket", label: "Lancio ufficiale o go-to-market", category: "business" },
  { name: "Lightbulb", label: "Soluzione creativa o brainstorming", category: "business" },
  { name: "Crown", label: "Clienti VIP o account strategici", category: "business" },
  { name: "PackageCheck", label: "Logistica inbound o controllo pezzi", category: "business" },
  { name: "Truck", label: "Consegna merci o logistica", category: "business" },
  { name: "Sparkles", label: "Nuova opportunità d'oro di business", category: "business" },
  { name: "Banknote", label: "Banconota contante di carta", category: "business" },
  { name: "HandCoins", label: "Scambio o ricezione monete", category: "business" },
  { name: "CircleDollarSign", label: "Moneta dollaro tonda", category: "business" },
  { name: "CircleEuro", label: "Moneta euro tonda", category: "business" },
  { name: "Gem", label: "Gemma preziosa diamanti valore", category: "business" },
  { name: "Landmark", label: "Banca filiale o istituto", category: "business" },
  { name: "Vault", label: "Cassaforte di sicurezza valori", category: "business" },
  { name: "Wallet2", label: "Portafoglio banconote alternativo", category: "business" },
  { name: "BadgeDollarSign", label: "Badge dollaro promozione lusso", category: "business" },
  { name: "BadgeEuro", label: "Badge euro certificazione prezzo", category: "business" },
  { name: "BadgeSwissFranc", label: "Badge franchi svizzeri valuta", category: "business" },
  { name: "BadgePound", label: "Badge sterlina inglese valuta", category: "business" },
  { name: "ReceiptCent", label: "Ricevuta contabile centesimi", category: "business" },
  { name: "ReceiptDollarSign", label: "Ricevuta fattura in dollari", category: "business" },
  { name: "ReceiptEuro", label: "Ricevuta fattura in euro", category: "business" },
  { name: "SquareDollarSign", label: "Pulsante quadrato dollaro risorsa", category: "business" },
  { name: "SquareEuro", label: "Pulsante quadrato euro risorsa", category: "business" },
  { name: "Store", label: "Ponto vendita negozio fisico", category: "business" },
  { name: "Tag", label: "Cartellino prezzo o offerta", category: "business" },
  { name: "Tags", label: "Etichette sconti o categorie", category: "business" }
];

export const INITIAL_ACTIVITIES: Activity[] = [
  { id: "sesso", name: "Sesso", iconName: "Heart", color: "rose", isCustom: false },
  { id: "caffe", name: "Caffè", iconName: "Coffee", color: "amber", isCustom: false },
  { id: "esercizi", name: "Esercizi", iconName: "Dumbbell", color: "emerald", isCustom: false },
  { id: "relax", name: "Relax", iconName: "Smile", color: "sky", isCustom: false },
  { id: "passeggiata", name: "Passeggiata", iconName: "Footprints", color: "emerald", isCustom: false },
  { id: "cinema", name: "Cinema", iconName: "Clapperboard", color: "indigo", isCustom: false },
  { id: "pranzo", name: "Pranzo", iconName: "Utensils", color: "amber", isCustom: false },
  { id: "cena", name: "Cena", iconName: "Utensils", color: "violet", isCustom: false },
  { id: "colazione", name: "Colazione", iconName: "Coffee", color: "sky", isCustom: false },
  { id: "spuntino", name: "Spuntino", iconName: "Apple", color: "emerald", isCustom: false },
  { id: "lite", name: "Lite", iconName: "Flame", color: "rose", isCustom: false },
  { id: "film", name: "Film", iconName: "Film", color: "indigo", isCustom: false },
  { id: "lettura", name: "Lettura", iconName: "BookOpen", color: "violet", isCustom: false },
  { id: "lavoro", name: "Lavoro", iconName: "Briefcase", color: "slate", isCustom: false },
  { id: "shopping", name: "Shopping", iconName: "ShoppingBag", color: "fuchsia", isCustom: false },
  { id: "compleanno", name: "Compleanno", iconName: "Cake", color: "rose", isCustom: false },
  { id: "affitto", name: "Affitto", iconName: "Home", color: "amber", isCustom: false },
  { id: "mutuo", name: "Mutuo", iconName: "Landmark", color: "indigo", isCustom: false },
  { id: "ballo", name: "Ballo", iconName: "HighHeel", color: "fuchsia", isCustom: false },
  { id: "danza", name: "Danza", iconName: "Music", color: "violet", isCustom: false },
  { id: "babyshower", name: "Baby Shower", iconName: "BabyShower", color: "rose", isCustom: false },
];
